require('dotenv').config({ path: require('path').join(__dirname, '../../../.env') });

import { PrismaClient, BadgeType } from '@prisma/client';

const prisma = new PrismaClient();

const badges = [
  // ==================== EVENT & SOCIAL BADGES ====================
  {
    type: BadgeType.FIRST_FACE,
    name: 'First Face',
    description: 'Welcome to the community! Attended your first event.',
    criteria: 'Attend 1 event',
    imageUrl: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=200&h=200&fit=crop',
    category: 'Events',
    tier: 'Bronze',
    points: 10,
    requiredCount: 1,
    criteriaConfig: {
      type: 'event_attendance',
      condition: 'total_events_attended',
      count: 1,
    },
  },
  {
    type: BadgeType.CAFE_FRIEND,
    name: 'Cafe Friend',
    description: 'Regular cafe meetup attendee - coffee and conversation expert!',
    criteria: 'Attend 3+ cafe meetups',
    imageUrl: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=200&h=200&fit=crop',
    category: 'Events',
    tier: 'Silver',
    points: 25,
    requiredCount: 3,
    criteriaConfig: {
      type: 'event_attendance',
      condition: 'event_type_count',
      eventType: 'CAFE_MEETUP',
      count: 3,
    },
  },
  {
    type: BadgeType.SUKAN_SQUAD_MVP,
    name: 'Sukan Squad MVP',
    description: 'Active sports participant - keeping fit with the community!',
    criteria: 'Attend 5+ sports events',
    imageUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=200&h=200&fit=crop',
    category: 'Events',
    tier: 'Gold',
    points: 50,
    requiredCount: 5,
    criteriaConfig: {
      type: 'event_attendance',
      condition: 'event_type_count',
      eventType: 'SPORTS',
      count: 5,
    },
  },
  {
    type: BadgeType.SOUL_NOURISHER,
    name: 'Soul Nourisher',
    description: 'Regular Ilm event participant - feeding your soul with knowledge.',
    criteria: 'Attend 5+ Ilm/knowledge events',
    imageUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=200&h=200&fit=crop',
    category: 'Events',
    tier: 'Gold',
    points: 50,
    requiredCount: 5,
    criteriaConfig: {
      type: 'event_attendance',
      condition: 'event_type_count',
      eventType: 'ILM',
      count: 5,
    },
  },
  {
    type: BadgeType.HELPERS_HAND,
    name: "Helper's Hand",
    description: 'Community volunteer - making a difference through service!',
    criteria: 'Volunteer at 3+ events',
    imageUrl: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=200&h=200&fit=crop',
    category: 'Community',
    tier: 'Silver',
    points: 40,
    requiredCount: 3,
    criteriaConfig: {
      type: 'event_attendance',
      condition: 'event_type_count',
      eventType: 'VOLUNTEER',
      count: 3,
    },
  },
  {
    type: BadgeType.CONNECTOR,
    name: 'Connector',
    description: 'Community builder - growing the network one friend at a time!',
    criteria: 'Refer 3+ activated users',
    imageUrl: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=200&h=200&fit=crop',
    category: 'Social',
    tier: 'Gold',
    points: 60,
    requiredCount: 3,
    criteriaConfig: {
      type: 'referral',
      condition: 'activated_referrals',
      count: 3,
    },
  },
  {
    type: BadgeType.TOP_FRIEND,
    name: 'Top Friend',
    description: 'Social butterfly - you know everyone in the community!',
    criteria: 'Make 10+ connections',
    imageUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=200&h=200&fit=crop',
    category: 'Social',
    tier: 'Gold',
    points: 50,
    requiredCount: 10,
    criteriaConfig: {
      type: 'connection',
      condition: 'accepted_connections',
      count: 10,
    },
  },
  {
    type: BadgeType.ICEBREAKER,
    name: 'Icebreaker',
    description: 'Made your first connection - breaking the ice!',
    criteria: 'Make 1 connection',
    imageUrl: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?w=200&h=200&fit=crop',
    category: 'Social',
    tier: 'Bronze',
    points: 10,
    requiredCount: 1,
    criteriaConfig: {
      type: 'connection',
      condition: 'accepted_connections',
      count: 1,
    },
  },
  {
    type: BadgeType.CERTIFIED_HOST,
    name: 'Certified Host',
    description: 'Event host - bringing people together!',
    criteria: 'Host 1+ event',
    imageUrl: 'https://images.unsplash.com/photo-1511578194003-00c80e42dc9b?w=200&h=200&fit=crop',
    category: 'Events',
    tier: 'Silver',
    points: 30,
    requiredCount: 1,
    criteriaConfig: {
      type: 'event_hosting',
      condition: 'events_hosted',
      count: 1,
    },
  },
  {
    type: BadgeType.STREAK_CHAMP,
    name: 'Streak Champ',
    description: 'Consistent event attendee - committed to the community!',
    criteria: 'Attend events for 4 consecutive weeks',
    imageUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=200&h=200&fit=crop',
    category: 'Events',
    tier: 'Gold',
    points: 75,
    requiredCount: 4,
    criteriaConfig: {
      type: 'streak',
      condition: 'consecutive_weeks',
      weeks: 4,
    },
  },
  {
    type: BadgeType.LOCAL_GUIDE,
    name: 'Local Guide',
    description: 'Explorer - discovering new places with the community!',
    criteria: 'Attend events in 5+ different locations',
    imageUrl: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=200&h=200&fit=crop',
    category: 'Events',
    tier: 'Gold',
    points: 50,
    requiredCount: 5,
    criteriaConfig: {
      type: 'event_attendance',
      condition: 'unique_locations',
      count: 5,
    },
  },
  {
    type: BadgeType.KIND_SOUL,
    name: 'Kind Soul',
    description: 'Positive vibes provider - spreading trust and kindness!',
    criteria: 'Give 10+ positive trust moments (4+ star ratings)',
    imageUrl: 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?w=200&h=200&fit=crop',
    category: 'Community',
    tier: 'Gold',
    points: 60,
    requiredCount: 10,
    criteriaConfig: {
      type: 'trust_moment',
      condition: 'positive_ratings_given',
      minRating: 4,
      count: 10,
    },
  },
  {
    type: BadgeType.KNOWLEDGE_SHARER,
    name: 'Knowledge Sharer',
    description: 'Community teacher - sharing wisdom and insights!',
    criteria: 'Submit 5+ helpful card game feedbacks',
    imageUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=200&h=200&fit=crop',
    category: 'Community',
    tier: 'Silver',
    points: 40,
    requiredCount: 5,
    criteriaConfig: {
      type: 'engagement',
      condition: 'card_game_feedbacks',
      count: 5,
    },
  },
  {
    type: BadgeType.ALL_ROUNDER,
    name: 'All-Rounder',
    description: 'Achievement master - collected multiple badges!',
    criteria: 'Earn 5+ unique badges',
    imageUrl: 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=200&h=200&fit=crop',
    category: 'Achievement',
    tier: 'Platinum',
    points: 100,
    requiredCount: 5,
    criteriaConfig: {
      type: 'meta',
      condition: 'badges_earned',
      count: 5,
    },
  },

  // ==================== COMMUNITY BADGES ====================
  {
    type: BadgeType.COMMUNITY_BUILDER,
    name: 'Community Builder',
    description: 'Created your own community - bringing people together!',
    criteria: 'Create 1 community',
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=200&h=200&fit=crop',
    category: 'Community',
    tier: 'Silver',
    points: 50,
    requiredCount: 1,
    criteriaConfig: {
      type: 'community',
      condition: 'communities_created',
      count: 1,
    },
  },
  {
    type: BadgeType.COMMUNITY_CHAMPION,
    name: 'Community Champion',
    description: 'Active member in multiple communities!',
    criteria: 'Join 3+ communities',
    imageUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=200&h=200&fit=crop',
    category: 'Community',
    tier: 'Silver',
    points: 40,
    requiredCount: 3,
    criteriaConfig: {
      type: 'community',
      condition: 'communities_joined',
      count: 3,
    },
  },
  {
    type: BadgeType.MODERATOR_PRO,
    name: 'Moderator Pro',
    description: 'Trusted community moderator - keeping the peace!',
    criteria: 'Become a moderator in any community',
    imageUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&h=200&fit=crop',
    category: 'Community',
    tier: 'Gold',
    points: 75,
    requiredCount: 1,
    criteriaConfig: {
      type: 'community',
      condition: 'moderator_role',
      count: 1,
    },
  },
  {
    type: BadgeType.COMMUNITY_LEADER,
    name: 'Community Leader',
    description: 'Managing a thriving community!',
    criteria: 'Manage a community with 50+ members',
    imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=200&h=200&fit=crop',
    category: 'Community',
    tier: 'Platinum',
    points: 150,
    requiredCount: 50,
    criteriaConfig: {
      type: 'community',
      condition: 'community_member_count',
      count: 50,
    },
  },
  {
    type: BadgeType.COMMUNITY_ORGANIZER,
    name: 'Community Organizer',
    description: 'Organized multiple community events!',
    criteria: 'Host 5+ community events',
    imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=200&h=200&fit=crop',
    category: 'Community',
    tier: 'Gold',
    points: 80,
    requiredCount: 5,
    criteriaConfig: {
      type: 'event_hosting',
      condition: 'community_events_hosted',
      count: 5,
    },
  },

  // ==================== MARKETPLACE BADGES ====================
  {
    type: BadgeType.FIRST_SALE,
    name: 'First Sale',
    description: 'Made your first sale on the marketplace!',
    criteria: 'Complete 1 sale as seller',
    imageUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=200&h=200&fit=crop',
    category: 'Marketplace',
    tier: 'Bronze',
    points: 20,
    requiredCount: 1,
    criteriaConfig: {
      type: 'marketplace',
      condition: 'sales_completed',
      count: 1,
    },
  },
  {
    type: BadgeType.TRUSTED_SELLER,
    name: 'Trusted Seller',
    description: 'Established seller with multiple successful transactions!',
    criteria: 'Complete 10+ sales',
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=200&h=200&fit=crop',
    category: 'Marketplace',
    tier: 'Gold',
    points: 100,
    requiredCount: 10,
    criteriaConfig: {
      type: 'marketplace',
      condition: 'sales_completed',
      count: 10,
    },
  },
  {
    type: BadgeType.POWER_BUYER,
    name: 'Power Buyer',
    description: 'Active marketplace buyer!',
    criteria: 'Purchase 10+ items',
    imageUrl: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=200&h=200&fit=crop',
    category: 'Marketplace',
    tier: 'Silver',
    points: 60,
    requiredCount: 10,
    criteriaConfig: {
      type: 'marketplace',
      condition: 'purchases_completed',
      count: 10,
    },
  },
  {
    type: BadgeType.MARKETPLACE_PRO,
    name: 'Marketplace Pro',
    description: 'Marketplace veteran with extensive trading history!',
    criteria: 'Complete 50+ total transactions',
    imageUrl: 'https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?w=200&h=200&fit=crop',
    category: 'Marketplace',
    tier: 'Platinum',
    points: 200,
    requiredCount: 50,
    criteriaConfig: {
      type: 'marketplace',
      condition: 'total_transactions',
      count: 50,
    },
  },
  {
    type: BadgeType.FIVE_STAR_SELLER,
    name: 'Five Star Seller',
    description: 'Maintained excellent seller rating!',
    criteria: '5-star average with 20+ reviews',
    imageUrl: 'https://images.unsplash.com/photo-1513135065346-a098a63a71ee?w=200&h=200&fit=crop',
    category: 'Marketplace',
    tier: 'Gold',
    points: 120,
    requiredCount: 20,
    criteriaConfig: {
      type: 'marketplace',
      condition: 'five_star_seller',
      minRating: 5.0,
      minReviews: 20,
    },
  },

  // ==================== VOUCH SYSTEM BADGES ====================
  {
    type: BadgeType.VOUCHED,
    name: 'Vouched',
    description: 'Received your first vouch - building trust!',
    criteria: 'Receive 1 vouch',
    imageUrl: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=200&h=200&fit=crop',
    category: 'Trust',
    tier: 'Bronze',
    points: 15,
    requiredCount: 1,
    criteriaConfig: {
      type: 'vouch',
      condition: 'vouches_received',
      status: 'ACTIVE',
      count: 1,
    },
  },
  {
    type: BadgeType.TRUST_BUILDER,
    name: 'Trust Builder',
    description: 'Building a solid reputation in the community!',
    criteria: 'Receive 3+ vouches',
    imageUrl: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=200&h=200&fit=crop',
    category: 'Trust',
    tier: 'Silver',
    points: 50,
    requiredCount: 3,
    criteriaConfig: {
      type: 'vouch',
      condition: 'vouches_received',
      status: 'ACTIVE',
      count: 3,
    },
  },
  {
    type: BadgeType.HIGHLY_VOUCHED,
    name: 'Highly Vouched',
    description: 'Highly trusted community member!',
    criteria: 'Receive 10+ vouches',
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=200&h=200&fit=crop',
    category: 'Trust',
    tier: 'Gold',
    points: 150,
    requiredCount: 10,
    criteriaConfig: {
      type: 'vouch',
      condition: 'vouches_received',
      status: 'ACTIVE',
      count: 10,
    },
  },
  {
    type: BadgeType.VOUCH_GIVER,
    name: 'Vouch Giver',
    description: 'Helping others build trust!',
    criteria: 'Give 5+ vouches',
    imageUrl: 'https://images.unsplash.com/photo-1531545514256-b1400bc00f31?w=200&h=200&fit=crop',
    category: 'Trust',
    tier: 'Silver',
    points: 40,
    requiredCount: 5,
    criteriaConfig: {
      type: 'vouch',
      condition: 'vouches_given',
      status: 'ACTIVE',
      count: 5,
    },
  },
  {
    type: BadgeType.COMMUNITY_VOUCHED,
    name: 'Community Vouched',
    description: 'Received a special community vouch!',
    criteria: 'Receive 1 community vouch',
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=200&h=200&fit=crop',
    category: 'Trust',
    tier: 'Gold',
    points: 75,
    requiredCount: 1,
    criteriaConfig: {
      type: 'vouch',
      condition: 'community_vouch_received',
      vouchType: 'COMMUNITY',
      count: 1,
    },
  },

  // ==================== TRAVEL & GUIDE BADGES ====================
  {
    type: BadgeType.GLOBE_TROTTER,
    name: 'Globe Trotter',
    description: 'Exploring different cities with the community!',
    criteria: 'Attend trips in 3+ different cities',
    imageUrl: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=200&h=200&fit=crop',
    category: 'Travel',
    tier: 'Silver',
    points: 50,
    requiredCount: 3,
    criteriaConfig: {
      type: 'travel',
      condition: 'cities_visited',
      count: 3,
    },
  },
  {
    type: BadgeType.ADVENTURE_SEEKER,
    name: 'Adventure Seeker',
    description: 'Regular trip participant - always ready for adventure!',
    criteria: 'Attend 5+ trip events',
    imageUrl: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=200&h=200&fit=crop',
    category: 'Travel',
    tier: 'Gold',
    points: 60,
    requiredCount: 5,
    criteriaConfig: {
      type: 'event_attendance',
      condition: 'event_type_count',
      eventType: 'TRIP',
      count: 5,
    },
  },
  {
    type: BadgeType.LOCAL_HOST,
    name: 'Local Host',
    description: 'Welcoming travelers into your home!',
    criteria: 'Host 1+ traveler through Homesurf',
    imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=200&h=200&fit=crop',
    category: 'Travel',
    tier: 'Silver',
    points: 50,
    requiredCount: 1,
    criteriaConfig: {
      type: 'homesurf',
      condition: 'bookings_as_host',
      status: 'COMPLETED',
      count: 1,
    },
  },
  {
    type: BadgeType.SUPER_HOST,
    name: 'Super Host',
    description: 'Exceptional Homesurf host with outstanding reviews!',
    criteria: '10+ positive Homesurf reviews',
    imageUrl: 'https://images.unsplash.com/photo-1560184897-ae75f418493e?w=200&h=200&fit=crop',
    category: 'Travel',
    tier: 'Gold',
    points: 100,
    requiredCount: 10,
    criteriaConfig: {
      type: 'homesurf',
      condition: 'positive_host_reviews',
      minRating: 4,
      count: 10,
    },
  },
  {
    type: BadgeType.TOUR_GUIDE,
    name: 'Tour Guide',
    description: 'Sharing your local knowledge with travelers!',
    criteria: 'Guide 5+ tours',
    imageUrl: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?w=200&h=200&fit=crop',
    category: 'Travel',
    tier: 'Gold',
    points: 80,
    requiredCount: 5,
    criteriaConfig: {
      type: 'berse_guide',
      condition: 'tours_completed',
      status: 'COMPLETED',
      count: 5,
    },
  },

  // ==================== ENGAGEMENT BADGES ====================
  {
    type: BadgeType.EARLY_ADOPTER,
    name: 'Early Adopter',
    description: 'One of the first members of the community!',
    criteria: 'Join in first 1000 users',
    imageUrl: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=200&h=200&fit=crop',
    category: 'Special',
    tier: 'Platinum',
    points: 200,
    requiredCount: 1000,
    criteriaConfig: {
      type: 'special',
      condition: 'early_adopter',
      maxUserNumber: 1000,
    },
  },
  {
    type: BadgeType.DAILY_ACTIVE,
    name: 'Daily Active',
    description: 'Consistent daily user - part of the routine!',
    criteria: 'Active 30 days in a row',
    imageUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=200&h=200&fit=crop',
    category: 'Engagement',
    tier: 'Gold',
    points: 100,
    requiredCount: 30,
    criteriaConfig: {
      type: 'engagement',
      condition: 'daily_active_streak',
      days: 30,
    },
  },
  {
    type: BadgeType.FEEDBACK_CHAMPION,
    name: 'Feedback Champion',
    description: 'Active reviewer helping others make decisions!',
    criteria: 'Leave 20+ helpful reviews',
    imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=200&h=200&fit=crop',
    category: 'Engagement',
    tier: 'Silver',
    points: 60,
    requiredCount: 20,
    criteriaConfig: {
      type: 'engagement',
      condition: 'reviews_given',
      count: 20,
    },
  },
  {
    type: BadgeType.CONVERSATION_STARTER,
    name: 'Conversation Starter',
    description: 'Social connector - always starting new conversations!',
    criteria: 'Start 50+ conversations',
    imageUrl: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?w=200&h=200&fit=crop',
    category: 'Social',
    tier: 'Silver',
    points: 50,
    requiredCount: 50,
    criteriaConfig: {
      type: 'engagement',
      condition: 'conversations_started',
      count: 50,
    },
  },
  {
    type: BadgeType.SUPER_RESPONDER,
    name: 'Super Responder',
    description: 'Always replying - great communicator!',
    criteria: 'Respond to 100+ messages',
    imageUrl: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?w=200&h=200&fit=crop',
    category: 'Social',
    tier: 'Gold',
    points: 75,
    requiredCount: 100,
    criteriaConfig: {
      type: 'engagement',
      condition: 'messages_sent',
      count: 100,
    },
  },

  // ==================== ACHIEVEMENT BADGES ====================
  {
    type: BadgeType.LEVEL_10,
    name: 'Level 10',
    description: 'Reached level 10 - growing strong!',
    criteria: 'Reach level 10',
    imageUrl: 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=200&h=200&fit=crop',
    category: 'Achievement',
    tier: 'Bronze',
    points: 50,
    requiredCount: 10,
    criteriaConfig: {
      type: 'achievement',
      condition: 'level_reached',
      level: 10,
    },
  },
  {
    type: BadgeType.LEVEL_25,
    name: 'Level 25',
    description: 'Reached level 25 - experienced member!',
    criteria: 'Reach level 25',
    imageUrl: 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=200&h=200&fit=crop',
    category: 'Achievement',
    tier: 'Silver',
    points: 100,
    requiredCount: 25,
    criteriaConfig: {
      type: 'achievement',
      condition: 'level_reached',
      level: 25,
    },
  },
  {
    type: BadgeType.LEVEL_50,
    name: 'Level 50',
    description: 'Reached level 50 - elite member!',
    criteria: 'Reach level 50',
    imageUrl: 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=200&h=200&fit=crop',
    category: 'Achievement',
    tier: 'Gold',
    points: 250,
    requiredCount: 50,
    criteriaConfig: {
      type: 'achievement',
      condition: 'level_reached',
      level: 50,
    },
  },
  {
    type: BadgeType.POINTS_MASTER,
    name: 'Points Master',
    description: 'Accumulated massive points - dedication rewarded!',
    criteria: 'Earn 10,000+ points',
    imageUrl: 'https://images.unsplash.com/photo-1571017418485-8a53bce3d623?w=200&h=200&fit=crop',
    category: 'Achievement',
    tier: 'Platinum',
    points: 500,
    requiredCount: 10000,
    criteriaConfig: {
      type: 'achievement',
      condition: 'total_points',
      points: 10000,
    },
  },
  {
    type: BadgeType.PERFECT_PROFILE,
    name: 'Perfect Profile',
    description: 'Completed every section of your profile!',
    criteria: 'Complete 100% of profile',
    imageUrl: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=200&h=200&fit=crop',
    category: 'Achievement',
    tier: 'Silver',
    points: 30,
    requiredCount: 100,
    criteriaConfig: {
      type: 'profile',
      condition: 'profile_completion',
      percentage: 100,
    },
  },
];

export async function seedBadges() {
  console.log('\n📛 Seeding badges...');
  
  for (const badge of badges) {
    await prisma.badge.upsert({
      where: { type: badge.type },
      update: {
        name: badge.name,
        description: badge.description,
        criteria: badge.criteria,
        imageUrl: badge.imageUrl,
        category: badge.category,
        tier: badge.tier,
        points: badge.points,
        requiredCount: badge.requiredCount,
        criteriaConfig: badge.criteriaConfig,
      },
      create: badge,
    });
  }
  
  const count = await prisma.badge.count();
  console.log(`✅ ${count} badges seeded successfully with dynamic criteria`);
}

async function main() {
  await seedBadges();
}

if (require.main === module) {
  main()
    .catch((e) => {
      console.error('❌ Badge seed failed:', e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
