#!/bin/bash

echo "=========================================="
echo "Railway Deployment Status Checker"
echo "=========================================="
echo ""

echo "📋 Your Railway Projects:"
railway list
echo ""

echo "=========================================="
echo "To check deployment status:"
echo "=========================================="
echo ""
echo "1. Link to staging environment:"
echo "   railway link"
echo "   - Select: berse-app"
echo "   - Select: staging"
echo "   - Select: berse-backend"
echo ""
echo "2. Check status:"
echo "   railway status"
echo ""
echo "3. View logs:"
echo "   railway logs"
echo ""
echo "4. To switch to production:"
echo "   railway link"
echo "   - Select: berse-app"
echo "   - Select: production"
echo "   - Select: berse-backend"
echo ""
echo "=========================================="
