#!/bin/bash

echo "=========================================="
echo "🚀 Railway Deployment Status Checker"
echo "=========================================="
echo ""

echo "📍 Current Railway Link:"
railway status 2>&1 || echo "Not linked or Railway CLI not found"
echo ""

echo "=========================================="
echo "📊 To Check Deployment Status:"
echo "=========================================="
echo ""
echo "🌐 OPTION 1: Via Railway Dashboard (Easiest)"
echo "   1. Visit: https://railway.app"
echo "   2. Click on 'berse-app' project"
echo "   3. Switch environment (staging/production) in dropdown"
echo "   4. Click 'berse-backend' service"
echo "   5. Click 'Deployments' tab"
echo "   6. Check latest deployment status"
echo ""
echo "=========================================="
echo ""
echo "💻 OPTION 2: Via Railway CLI"
echo ""
echo "For STAGING backend:"
echo "   railway link"
echo "   (Select: berse-app → staging → berse-backend)"
echo "   railway status"
echo "   railway logs --tail 50"
echo ""
echo "For PRODUCTION backend:"
echo "   railway link"
echo "   (Select: berse-app → production → berse-backend)"
echo "   railway status"
echo "   railway logs --tail 50"
echo ""
echo "=========================================="
echo ""
echo "🔗 Getting Your Deployment URLs:"
echo ""
echo "In Railway Dashboard:"
echo "   1. Select environment (staging/production)"
echo "   2. Click 'berse-backend' service"
echo "   3. Click 'Settings' → 'Domains'"
echo "   4. Copy the Railway-provided URL"
echo ""
echo "=========================================="
echo ""
echo "🧪 Test Your Deployment:"
echo ""
echo "Once you have the URL, test the health endpoint:"
echo "   curl https://your-railway-url.up.railway.app/health"
echo ""
echo "Expected response:"
echo '   {"status":"ok","timestamp":"..."}'
echo ""
echo "=========================================="

# Try to get Railway project info
echo ""
echo "🔍 Checking Railway connection..."
railway whoami 2>&1 | head -5
echo ""

echo "=========================================="
echo "📝 Next: Check your Railway dashboard at:"
echo "   https://railway.app"
echo "=========================================="
